# Generated by Django 6.0.1 on 2026-03-13 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_odia', models.CharField(max_length=200, verbose_name='ନାମ (ଓଡ଼ିଆ)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Name (English)')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ଶ୍ରେଣୀ',
                'verbose_name_plural': 'ଶ୍ରେଣୀଗୁଡ଼ିକ',
                'ordering': ['name_odia'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_odia', models.CharField(max_length=200, verbose_name='ଶୀର୍ଷକ (ଓଡ଼ିଆ)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title (English)')),
                ('description_odia', models.TextField(blank=True, verbose_name='ବର୍ଣ୍ଣନା (ଓଡ଼ିଆ)')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='ଛବି')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ପ୍ରମୁଖ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='ଅପଲୋଡ ସମୟ')),
            ],
            options={
                'verbose_name': 'ଗ୍ୟାଲେରୀ ଛବି',
                'verbose_name_plural': 'ଗ୍ୟାଲେରୀ ଛବିଗୁଡ଼ିକ',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='ବର୍ଷ')),
                ('title_odia', models.CharField(max_length=300, verbose_name='ଶୀର୍ଷକ (ଓଡ଼ିଆ)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Title (English)')),
                ('description_odia', models.TextField(verbose_name='ବର୍ଣ୍ଣନା (ଓଡ଼ିଆ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='କ୍ରମ')),
            ],
            options={
                'verbose_name': 'ସମୟରେଖା ଘଟଣା',
                'verbose_name_plural': 'ସମୟରେଖା ଘଟଣାବଳୀ',
                'ordering': ['year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_odia', models.CharField(max_length=300, verbose_name='ଶୀର୍ଷକ (ଓଡ଼ିଆ)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Title (English)')),
                ('slug', models.SlugField(unique=True)),
                ('content_odia', models.TextField(verbose_name='ବିଷୟବସ୍ତୁ (ଓଡ଼ିଆ)')),
                ('content_en', models.TextField(blank=True, verbose_name='Content (English)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='ଛବି')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ପ୍ରମୁଖ ଖବର')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ସୃଷ୍ଟି ସମୟ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ଅପଡେଟ ସମୟ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='portal.category', verbose_name='ଶ୍ରେଣୀ')),
            ],
            options={
                'verbose_name': 'ପ୍ରବନ୍ଧ',
                'verbose_name_plural': 'ପ୍ରବନ୍ଧଗୁଡ଼ିକ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_odia', models.CharField(max_length=300, verbose_name='ଶୀର୍ଷକ (ଓଡ଼ିଆ)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Title (English)')),
                ('description_odia', models.TextField(blank=True, verbose_name='ବର୍ଣ୍ଣନା (ଓଡ଼ିଆ)')),
                ('file', models.FileField(upload_to='documents/', verbose_name='ଫାଇଲ (PDF)')),
                ('file_type', models.CharField(default='PDF', editable=False, max_length=50)),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='ଡାଉନଲୋଡ ସଂଖ୍ୟା')),
                ('is_active', models.BooleanField(default=True, verbose_name='ସକ୍ରିୟ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='ଅପଲୋଡ ସମୟ')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='portal.category', verbose_name='ଶ୍ରେଣୀ')),
            ],
            options={
                'verbose_name': 'ଦଲିଲ',
                'verbose_name_plural': 'ଦଲିଲଗୁଡ଼ିକ',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='ଫୋନ')),
                ('bio', models.TextField(blank=True, verbose_name='ପରିଚୟ')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='ସଦସ୍ୟତା ସମୟ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ବ୍ୟବହାରକାରୀ ପ୍ରୋଫାଇଲ',
                'verbose_name_plural': 'ବ୍ୟବହାରକାରୀ ପ୍ରୋଫାଇଲଗୁଡ଼ିକ',
            },
        ),
    ]
