# Generated by Django 6.0.1 on 2026-03-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_odia', models.CharField(max_length=300, verbose_name='ଶୀର୍ଷକ (ଓଡ଼ିଆ)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Title (English)')),
                ('description_odia', models.TextField(blank=True, verbose_name='ବର୍ଣ୍ଣନା (ଓଡ଼ିଆ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('file_path', models.CharField(max_length=500, verbose_name='ଫାଇଲ ପଥ')),
                ('file_size', models.CharField(blank=True, max_length=50, verbose_name='ଫାଇଲ ଆକାର')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='ଡାଉନଲୋଡ ସଂଖ୍ୟା')),
                ('is_active', models.BooleanField(default=True, verbose_name='ସକ୍ରିୟ')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='ଯୋଡ଼ାଯାଇଥିବା ସମୟ')),
            ],
            options={
                'verbose_name': 'ପୁସ୍ତକ',
                'verbose_name_plural': 'ପୁସ୍ତକଗୁଡ଼ିକ',
                'ordering': ['title_odia'],
            },
        ),
    ]
